### ISSUE TITLE
MetaFed hyperparameters?

### ISSUE THREAD

**Issue by Buhua-Liu** [microsoft/PersonalizedFL#2]
Hi, 

Thanks for sharing the code. The hyperparameters for fedmeta seems missing in the `run.sh`, so I just run `python main.py --alg metafed --dataset medmnist --iters 300 --wk_iters 1 --non_iid_alpha 0.1 --model_momentum 0.3`, and I got an average accuracy 54.53. But the accuracy in the [benchmark](https://github.com/microsoft/PersonalizedFL#benchmark) is 83.87, and which is 90.81 in Table 3 of your [paper](https://arxiv.org/pdf/2206.08516.pdf).

![image](https://user-images.githubusercontent.com/55881942/183113496-e7f953c7-fd70-4ee0-8d07-3c081cdf3ad9.png)

Thanks for your attention!

**Comment by lw0517** [comment]
Thank you for your question. We have revised run.sh. Please refer to the latest version. Please utilize the same splits of data and the same environment for re-implementations. This open-source library did not exist when we performed experiments on MetaFed. Therefore, there might be some differences in results due to different environments, data splits, and some other factors.
