### ISSUE TITLE
changing partition data way

### ISSUE THREAD

**Issue by sanywright13** [microsoft/PersonalizedFL#36]
Hello ,
i'm training this code for medmnist dataset everythings goes good but when i change the partiton data way to either random  or when i change the --non_iid_alpha argument to something not in (0.1 or 0.01) (because as i see this partitions are already in split directory ) it raise an error , 

`File "/home/sanaa/PHD/fedsim/PersonalizedFL/main.py", line 75, in <module>
    train_loaders, val_loaders, test_loaders = get_data(args.dataset)(args)
  File "/home/sanaa/PHD/fedsim/PersonalizedFL/datautil/prepare_data.py", line 201, in medmnist
    trd, vad, ted = getlabeldataloader(args, data)
  File "/home/sanaa/PHD/fedsim/PersonalizedFL/datautil/prepare_data.py", line 187, in getlabeldataloader
    trl, val, tel = getdataloader(args, data)
  File "/home/sanaa/PHD/fedsim/PersonalizedFL/datautil/datasplit.py", line 315, in getdataloader
    tmparr = np.array(tmparr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (60,) + inhomogeneous`

**Comment by lw0517** [comment]
I'm truly sorry, but we cannot reproduce your error. We have tried different hyperparameters, including random splitting and various non_iid_alpha values, and the program executed smoothly in all cases. Perhaps you need to provide more details, such as the script being executed and the organization of files, in order to facilitate a more detailed analysis of the root cause of the error.
![image](https://github.com/microsoft/PersonalizedFL/assets/31000480/c9ca715b-7efe-41f2-86dd-ab7027a5af15)
![image](https://github.com/microsoft/PersonalizedFL/assets/31000480/6b490215-10a8-4d60-b277-d12fb8f8911e)
![image](https://github.com/microsoft/PersonalizedFL/assets/31000480/a542686b-1d76-42d5-a894-2a954369a5a3)

**Comment by sanywright13** [comment]
the path of the dataset is ./PersonalizedFL/data/medmnist

**Comment by sanywright13** [comment]
i suspect that the problem is with the latest numpy version , because when i changing to 
```
>>> import numpy as np
>>> np.__version__
'1.23.0'
```
the code works just Fine.
